name: background_changer
description: 사용자 사진에서 배경을 교체하는 앱
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  google_ml_kit: ^0.20.0
  tflite_flutter: ^0.11.0
  image: ^4.1.3
  permission_handler: ^12.0.0+1
  google_mlkit_selfie_segmentation: ^0.10.0
  share_plus: ^10.1.4
  # image_gallery_saver 제거

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
